#!/bin/bash
# --------------------------------------------------------------------
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------------------------------------------

sudo cp /opt/openboard/library/applications/plot-board.wgt/plot-board.sh /usr/local/bin/
sudo cp /opt/openboard/library/applications/plot-board.wgt/plot-board.service /etc/systemd/system/

sudo chmod 744 /usr/local/bin/plot-board.sh
sudo chmod 664 /etc/systemd/system/plot-board.service

sudo systemctl daemon-reload
sudo systemctl enable plot-board.service

sudo service plot-board start

exit 0